---
title: "Projects"
format: html
---

---
title: "Projects"
format: html
---

## The Role of Sports Statistics in Evaluating College Quarterbacks (2025)

### Summary
This project investigates the feasibility of using common college football quarterback statistics to predict NFL draft outcomes. It focuses on determining whether these statistics can accurately predict whether a quarterback will be drafted and identifying the most significant features influencing draft decisions.

### Description
The project addresses two main research questions: whether common quarterback statistics can predict NFL draft outcomes, and if so, what features most significantly influence these outcomes. Key elements of the project include:

- **Data Sourcing and Transformation**: Data was sourced from college football sports reference pages and normalized within players' conferences to account for variances in competition levels. A focus was maintained on players who played significant minutes and had a substantial amount of pass attempts.

- **Model Development and Evaluation**: Different statistical models, including Random Forest and Boosting models, were developed to predict the drafted status of quarterbacks. Techniques like weighting and undersampling were used to handle class imbalances in the data.

- **Feature Importance and SHAP Values**: After model training, feature importances were analyzed using built-in tree model methods and SHAP values. These analyses helped identify which statistics are most predictive of a quarterback being drafted.

- **Draftability Index**: Developed a "Draftability Index" which uses SHAP values to weight quarterback statistics, providing a simplified and powerful tool to assess a quarterback's likelihood of being drafted.

### My Role
I completed this project on a team of six. I spearheaded the data analysis, utilizing advanced statistical models and machine learning techniques to predict NFL draft likelihoods based on college performance, contributing to a deeper understanding of predictive sports analytics.

### Technologies Used
- **Python** for data processing and modeling.
- **Scikit-learn** for machine learning algorithms.
- **SHAP (Shapley Additive Explanations)** for interpreting model outputs.

### Results
- Achieved a nuanced understanding of how various quarterback statistics influence NFL draft outcomes.
- Developed models with up to 90% recall in predicting whether quarterbacks would be drafted, using undersampling methods to improve model performance.

### Files
- [Annotated Statistics 140XP Final Poster](/annotated-Stats_140XP_Final_Poster.pdf)

---

### Project Insights
This project provides valuable insights into the predictive power of college football quarterback statistics on NFL draft outcomes. It offers practical applications for NFL scouting teams and aspiring quarterbacks, highlighting the importance of specific skills and achievements in increasing draftability.

---

## Unsupervised Bias Detection in College Student Newspapers (2023)

### Summary
This project introduces an innovative, largely automated pipeline for unsupervised sentiment analysis to detect media bias in college newspaper archives. The system is designed to streamline the extraction and analysis of data, enabling precise interpretations of media bias with minimal human intervention. This approach significantly advances the field by providing a method to objectively understand biases within student newspaper sources.

### Description
The project centered on developing a sophisticated data collection and sentiment analysis pipeline. Key responsibilities and achievements include:

- **Advanced Data Collection**: Implemented extensive research and data collection across various media outlets using advanced scraping techniques. This included optimizing the process for multistage content retrieval, which allowed for the extraction of data from complex archive sites that automated tools typically fail to navigate.

- **Automated Sentiment Analysis Pipeline**: Played a pivotal role in creating a predominantly automated pipeline for unsupervised sentiment analysis. This system facilitated the streamlined extraction and analysis of text data, significantly enhancing the efficiency and accuracy of media bias detection.

- **Bias Detection and Analysis**: Leveraged computational social science expertise to assist in the creation of an analytical tool that generates bias scores. This tool serves as a guide toward more balanced and nuanced consumption of news, employing sophisticated machine learning models to classify and analyze the sentiment of texts.

- **Research Impact**: The complete method facilitates the extraction of nuanced insights with minimal assumptions, paving the way for a more objective understanding of bias within student newspaper sources.

### My Role
A total of eight interns on the Olami Data Team contributed to this project, with four primary contributors. As co-first author, I designed and implemented our web scraping pipeline for data collection. I then mentored two new team members who continuted collecting data using our pipeline and played a key role in creating an automated sentiment analysis pipeline to streamline bias detection in college media. 

### Technologies Used
- **Python** for data processing and machine learning.
- **NLTK and BART (HuggingFace)** for natural language processing and sentiment analysis.
- **Scikit-learn** for implementing unsupervised learning models.

### Results
- Developed a robust model that can effectively differentiate between biased and unbiased content.
- Created a visualization dashboard to represent the outcomes of the bias detection and sentiment analysis.

### Files
- [Unsupervised Bias Detection - Full Report](/UnsupervisedBias.pdf)
- [Complete Workflow Documentation](/complete_workflow.pdf)

---

### Project Insights
This project not only provided insights into the prevalence of bias in media but also showcased the potential of machine learning in automating the detection of such biases. It serves as a foundation for further research into automated media monitoring tools that can assist in creating a balanced informational environment.
